Repository 33-ohoh/33-ohoh, pull requests merged in 2024-01, with the labels that each got.

#4 [Design] 글로벌 스타일 생성 및 CSS 리셋
  apps/web/app/globals.css
  apps/web/app/layout.tsx
  packages/ui/.eslintrc.js
  packages/ui/package.json
  packages/ui/src/common.ts
Labels: style, feat

#9 [Feat] swr 설치 및 api util 구현 #8
  apps/web/app/apis/log.ts
  apps/web/app/hooks/swr/useLogs.ts
  apps/web/app/types/log.ts
  apps/web/app/utils/fetcher.ts
  apps/web/package.json
  package-lock.json
  turbo.json
Labels: feat

#11 [Feat] 텍스트 에디터 컴포넌트 구성 #6
  apps/web/app/log/page.tsx
  package-lock.json
  packages/ui/package.json
  packages/ui/src/quillEditor.tsx
Labels: feat

#14 Feat: 디자인 시스템 구축 #13
  package-lock.json
  packages/ui/.babelrc.js
  packages/ui/.eslintrc.js
  packages/ui/babel.config.js
  packages/ui/designToken.stylex.ts
  packages/ui/next.config.js
  packages/ui/package.json
Labels: feat

#15 [Fix] 디자인 토큰 위치로 인한 커밋 문제 해결
  packages/ui/src/designToken.stylex.ts
Labels: bug, Chore

#17 [Feat} HOT로그 컴포넌트 제작#5
  apps/web/app/main/page.tsx
  apps/web/app/page.tsx
  packages/ui/package.json
  packages/ui/src/icon.tsx
  packages/ui/src/main/hotLogCard.tsx
  packages/ui/src/main/hotLogList.tsx
  packages/ui/src/main/hotLogSection.tsx
Labels: feat

#19 [Fix] 디자인 시스템 변수가 web에서 적용되지 않는 문제 해결 #18
  apps/web/app/log/page.tsx
  apps/web/next.config.js
  package-lock.json
  package.json
  packages/ui/.babelrc.js
  packages/ui/package.json
Labels: bug, style

#16 [Feat] 마이페이지 사이드 및 관심로그 컴포넌트 구성
  apps/web/app/edit-mypage/page.tsx
  apps/web/app/log/page.tsx
  apps/web/app/main/page.tsx
  apps/web/app/mypage/page.tsx
  apps/web/app/page.tsx
  apps/web/next.config.js
  packages/ui/.babelrc.js
  packages/ui/package.json
  packages/ui/src/card.tsx
  packages/ui/src/edit-mypage/EditMypageLayout.tsx
  packages/ui/src/edit-mypage/ImageUpload.tsx
  packages/ui/src/edit-mypage/InputForm.tsx
  packages/ui/src/icon.tsx
  packages/ui/src/main/hotLogCard.tsx
  packages/ui/src/main/hotLogList.tsx
  packages/ui/src/main/hotLogSection.tsx
  packages/ui/src/mypage/asideContainer.tsx
  packages/ui/src/mypage/infoItem.tsx
  packages/ui/src/mypage/infoList.tsx
  packages/ui/src/mypage/interestLog.tsx
  packages/ui/src/mypage/logButton.tsx
  packages/ui/src/mypage/logCard.tsx
  packages/ui/src/mypage/mainContainer.tsx
  packages/ui/src/mypage/profileBox.tsx
  packages/ui/tsconfig.json
Labels: style, feat, merge conflict

#22 [Fix] 폴더구조 변경
  apps/web/apis/log.ts
  apps/web/app/Provider.tsx
  apps/web/app/edit-mypage/page.tsx
  apps/web/app/find-password/page.tsx
  apps/web/app/log/page.tsx
  apps/web/app/login/page.tsx
  apps/web/app/mypage/page.tsx
  apps/web/app/page.tsx
  apps/web/app/signup/page.tsx
  apps/web/components/Counter.tsx
  apps/web/components/edit-mypage/EditMypageLayout.tsx
  apps/web/components/edit-mypage/ImageUpload.tsx
  apps/web/components/edit-mypage/InputForm.tsx
  apps/web/components/mypage/AsideContainer.tsx
  apps/web/components/mypage/InfoItem.tsx
  apps/web/components/mypage/InfoList.tsx
  apps/web/components/mypage/InterestLog.tsx
  apps/web/components/mypage/LogButton.tsx
  apps/web/components/mypage/LogCard.tsx
  apps/web/components/mypage/MainContainer.tsx
  apps/web/components/mypage/ProfileBox.tsx
  apps/web/hooks/redux/index.ts
  apps/web/hooks/swr/useLogs.ts
  apps/web/store/counterSlice.ts
  apps/web/store/store.ts
  apps/web/types/log.ts
  apps/web/utils/fetcher.ts
Labels: merge conflict, urgent

#25 [Chore] 테일윈드 설치 작업
  apps/web/app/globals.css
  apps/web/app/page.tsx
  apps/web/package.json
  apps/web/postcss.config.js
  apps/web/tailwind.config.js
  package-lock.json
Labels: style, urgent

#31 [Feat] tailwind로 디자인시스템 다시 구축#28
  apps/web/app/globals.css
  apps/web/postcss.config.js
  apps/web/tailwind.config.js
  package-lock.json
Labels: feat

#32 [Feat] 로그인 회원가입 비밀번호찾기 회원 탈퇴의 로직 구현 #10
  apps/web/apis/auth.ts
  apps/web/apis/log.ts
  apps/web/app/find-password/page.tsx
  apps/web/app/login/page.tsx
  apps/web/app/signup/page.tsx
  apps/web/components/find-password/ChangePasswordForm.tsx
  apps/web/components/find-password/FindPasswordForm.tsx
  apps/web/components/signup/InterestAndPrivacyForm.tsx
  apps/web/components/signup/SignUpSuccess.tsx
  apps/web/components/signup/SignupForm.tsx
  apps/web/components/signup/SignupTerm.tsx
  apps/web/store/loginSlice.ts
  apps/web/store/signupSlice.ts
  apps/web/store/store.ts
  apps/web/types/auth.ts
  apps/web/types/log.ts
  apps/web/types/response.ts
  apps/web/types/user.ts
  apps/web/utils/fetcher.ts
  apps/web/utils/withAuth.tsx
  apps/web/utils/withGuest.tsx
  turbo.json
Labels: feat

#34 [Feat] SVG 아이콘 컴포넌트화
  packages/ui/src/svg/ProviderIcon.tsx
Labels: style, feat

#36 [Feat] hotLog 슬라이드 구현 #35
  apps/web/apis/log.ts
  apps/web/app/globals.css
  apps/web/app/login/page.tsx
  apps/web/app/main/page.tsx
  apps/web/app/page.tsx
  apps/web/app/signup/page.tsx
  apps/web/components/main/HotLogCard.tsx
  apps/web/components/main/HotLogCardList.tsx
  apps/web/types/hotLogCard.ts
  apps/web/utils/fetcher.ts
  package-lock.json
  package.json
  packages/ui/.eslintrc.js
  packages/ui/package.json
  packages/ui/src/designToken.stylex.ts
  packages/ui/src/icon.tsx
Labels: feat

#37 [Feat] Mypage 메인 마크업 및 아이콘 컴포넌트화
  apps/web/app/mypage/page.tsx
  apps/web/components/mypage/AsideContainer.tsx
  apps/web/components/mypage/InfoItem.tsx
  apps/web/components/mypage/InfoList.tsx
  apps/web/components/mypage/LogButton.tsx
  apps/web/components/mypage/LogCard.tsx
  apps/web/components/mypage/MainContainer.tsx
  apps/web/components/mypage/ProfileBox.tsx
  packages/ui/.eslintrc.js
  packages/ui/src/public/boy-chat-profile.png
  packages/ui/src/public/boy-coding.png
  packages/ui/src/public/boy-computer.png
  packages/ui/src/public/boy-tell.png
  packages/ui/src/public/default-image.png
  packages/ui/src/public/logo-google.png
  packages/ui/src/public/logo-kakao.png
  packages/ui/src/public/logo-naver.png
  packages/ui/src/svg/IconComponents.tsx
Labels: style, feat

#42 [Update] 아이콘 컴포넌트 props 수정
  packages/ui/src/svg/IconComponents.tsx
Labels: style

#40 [Feat] stepper ui 컴포넌트 구현 #33
  packages/ui/package.json
  packages/ui/src/stepper.tsx
Labels: feat
