Repository 33-ohoh/33-ohoh, pull requests merged in 2024-02, with the labels that each got.

#45 [Feat] 필터 태그 구현 #44
  apps/web/app/main/page.tsx
  apps/web/components/main/FilterTag.tsx
  apps/web/components/main/FilterTagList.tsx
  apps/web/components/main/LogSection.tsx
  apps/web/package.json
  apps/web/tailwind.config.ts
  apps/web/types/filterTag.ts
  package-lock.json
  package.json
Labels: feat

#47 [Feat] 로그 작성 페이지 마크업, 스타일링 #12
  apps/web/app/log/page.tsx
  apps/web/components/log/templateModal.tsx
  apps/web/public/recommendedThumbnail.png
  packages/ui/package.json
  packages/ui/src/common.ts
  packages/ui/src/quillEditor.css
  packages/ui/src/quillEditor.tsx
  packages/ui/src/svg/IconComponents.tsx
Labels: style, feat

#48 [Feat] mypage 메인 컨테이너 작업
  apps/docs/public/circles.svg
  apps/web/app/api/mypage/route.ts
  apps/web/app/globals.css
  apps/web/app/mypage/layout.tsx
  apps/web/components/mypage/InfoList.tsx
  apps/web/components/mypage/LogButton.tsx
  apps/web/components/mypage/LogCard.tsx
  apps/web/components/mypage/MainContainer.tsx
  apps/web/components/mypage/Pagination.tsx
  apps/web/components/mypage/ProfileBox.tsx
  apps/web/components/mypage/Visiting.tsx
  apps/web/next.config.js
  packages/ui/package.json
  packages/ui/src/icon.tsx
  packages/ui/src/svg/IconComponents.tsx
  packages/ui/src/svg/ProviderIcon.tsx
  packages/ui/tailwind.config.ts
Labels: refactor, feat

#55 [Feat] divier 컴포넌트 구현 #50
  packages/ui/src/divider.tsx
Labels: feat

#53 [Feat] 로그인에서 사용되는 input 컴포넌트 구현 #49
  apps/web/app/globals.css
  apps/web/constants/errorMessages.ts
  apps/web/constants/patterns.ts
  packages/ui/src/input.tsx
Labels: feat

#57 [Update] IconComponents svg 컴포넌트 리팩토링
  apps/web/app/page.tsx
  apps/web/components/mypage/LogButton.tsx
  packages/ui/package.json
  packages/ui/src/icon/IconComponents.tsx
  packages/ui/src/icon/index.tsx
  packages/ui/src/public/boy-chat-profile.png
  packages/ui/src/public/boy-coding.png
  packages/ui/src/public/boy-computer.png
  packages/ui/src/public/boy-tell.png
  packages/ui/src/public/default-image.png
  packages/ui/src/public/logo-google.png
  packages/ui/src/public/logo-kakao.png
  packages/ui/src/public/logo-naver.png
  packages/ui/src/svg/IconComponents.tsx
Labels: refactor

#54 [Feat] 로그인에서 사용되는 checkbox 컴포넌트 구현 #51
  packages/ui/src/checkbox.tsx
  packages/ui/src/icon.tsx
Labels: feat

#63 [Design] 로그 작성 페이지 팝업 구성 #46
  apps/web/app/globals.css
  apps/web/app/log/page.tsx
  apps/web/components/log/DraftModal.tsx
  apps/web/components/log/templateModal.tsx
  packages/ui/package.json
Labels: style, feat

#64 [Fix] 테일윈드 설정 문제로 인한 오류 해결 #62
  packages/ui/package.json
  packages/ui/tailwind.config.ts
Labels: bug, style

#66 [Feat] 마이페이지 페이지네이션 기능 구현
  apps/web/app/mypage/page.tsx
  apps/web/components/mypage/AsideContainer.tsx
  apps/web/components/mypage/InfoList.tsx
  apps/web/components/mypage/LogButton.tsx
  apps/web/components/mypage/LogCard.tsx
  apps/web/components/mypage/MainContainer.tsx
  apps/web/components/mypage/Pagination.tsx
  apps/web/components/mypage/ProfileBox.tsx
  apps/web/store/selectLogSlice.ts
  apps/web/store/store.ts
  packages/ui/package.json
  packages/ui/src/button.tsx
  packages/ui/src/radioField.tsx
Labels: feat

#68 [Reactor] 공용 카드 컴포넌트 수정
  packages/ui/package.json
  packages/ui/src/CardBottom.tsx
  packages/ui/src/CardTop.tsx
  packages/ui/src/card.tsx
  packages/ui/src/icon/IconComponents.tsx
  packages/ui/src/icon/index.tsx
Labels: refactor

#69 [Feat] 게시물 조회 페이지 구성 #65
  apps/web/app/log/[id]/page.tsx
  apps/web/app/log/page.tsx
  apps/web/package.json
  package-lock.json
  packages/ui/package.json
Labels: style, feat

#71 [Feat] 게시물 DB저장 및 저장 성공시 로직 구현 #70
  apps/web/app/log-success/[id]/page.tsx
  apps/web/app/log/[id]/page.tsx
  apps/web/app/log/page.tsx
  packages/ui/src/quillEditor.tsx
Labels: enhancement, style, feat

#73 [Feat] 메인페이지 필터 및 정렬 기능 구현 #72
  apps/web/apis/logList.ts
  apps/web/app/page.tsx
  apps/web/components/main/FilterSort.tsx
  apps/web/components/main/FilterTag.tsx
  apps/web/components/main/FilterTagList.tsx
  apps/web/components/main/HotLogCard.tsx
  apps/web/components/main/HotLogCardList.tsx
  apps/web/components/main/LogCard.tsx
  apps/web/components/main/LogCardList.tsx
  apps/web/components/main/LogSection.tsx
  apps/web/public/mainBanner.png
  apps/web/types/hotLogCard.ts
  apps/web/types/logcard.ts
  package-lock.json
  package.json
  packages/ui/src/icon.tsx
  packages/ui/src/icon/IconComponents.tsx
  packages/ui/src/icon/index.tsx
Labels: feat

#77 [Fix] 충돌로 인한 코드 해결
  package-lock.json
  packages/ui/package.json
Labels: bug

#80 [Feat] header제작 및 페이지 연결 #79
  apps/web/app/following-log/page.tsx
  apps/web/app/latest-log/page.tsx
  apps/web/app/layout.tsx
  apps/web/app/page.tsx
  apps/web/app/question-log/page.tsx
  apps/web/app/recruit/page.tsx
  apps/web/components/main/Header.tsx
  apps/web/components/main/HotLogCardList.tsx
  packages/ui/src/icon/IconComponents.tsx
  packages/ui/src/icon/index.tsx
Labels: feat

#81 [Feat] 로그 업로드시 썸네일 설정 기능 구성 #74
  apps/web/app/log/[id]/page.tsx
  apps/web/app/log/page.tsx
Labels: enhancement, feat

#85 [Feat] footer 컴포넌트 제작 #84
  apps/web/app/layout.tsx
  apps/web/components/main/Footer.tsx
  apps/web/public/google.png
  apps/web/public/kakao.png
  apps/web/public/naver.png
  packages/ui/src/icon/IconComponents.tsx
  packages/ui/src/icon/index.tsx
Labels: feat

#86 [Feat] 회원가입 페이지 구현 #59
  apps/web/apis/auth.ts
  apps/web/app/globals.css
  apps/web/app/layout.tsx
  apps/web/app/signup/page.tsx
  apps/web/components/main/FilterTag.tsx
  apps/web/components/signup/InterestAndPrivacyForm.tsx
  apps/web/components/signup/SignUpSuccess.tsx
  apps/web/components/signup/SignupForm.tsx
  apps/web/components/signup/SignupTerm.tsx
  apps/web/constants/errorMessages.ts
  apps/web/constants/terms.ts
  apps/web/public/signup-success.svg
  apps/web/store/signupSlice.ts
  apps/web/types/user.ts
  apps/web/utils/fetcher.ts
  packages/tailwind-config/tailwind.config.ts
  packages/ui/package.json
  packages/ui/src/button.tsx
  packages/ui/src/checkbox.tsx
  packages/ui/src/icon/IconComponents.tsx
  packages/ui/src/icon/index.tsx
  packages/ui/src/input.tsx
Labels: feat

#88 [Feat] 내가 쓴 댓글 페이지 데이터 패칭 및 페이지네이션
  apps/web/app/api/mypage/recentlog/route.ts
  apps/web/app/api/mypage/replies/route.ts
  apps/web/app/globals.css
  apps/web/app/mypage/mycomments/page.tsx
  apps/web/app/mypage/mylog/page.tsx
  apps/web/app/mypage/page.tsx
  apps/web/app/mypage/recentlog/page.tsx
  apps/web/app/mypage/replies/page.tsx
  apps/web/app/mypage/savelog/page.tsx
  apps/web/components/mypage/InfoList.tsx
  apps/web/components/mypage/Pagination.tsx
  apps/web/components/mypage/replies/ReplieCard.tsx
  apps/web/store/selectLogSlice.ts
  apps/web/store/store.ts
Labels: feat

#90 [Fix] pagination 상태 수정
  apps/web/app/mypage/mylog/page.tsx
Labels: bug

#92 [Feat] 메인페이지 페이지네이션 구현 #91
  apps/web/apis/logList.ts
  apps/web/components/main/HotLogCardList.tsx
  apps/web/components/main/LogCardList.tsx
  apps/web/components/main/Pagination.tsx
Labels: feat

#94 [Feat] 메인페이지, 마이페이지 게시물 관련 페이지들 연결 #89
  apps/web/app/main/page.tsx
  apps/web/components/main/Footer.tsx
  apps/web/components/main/Header.tsx
  apps/web/components/main/HotLogCard.tsx
  apps/web/components/main/LogCard.tsx
  apps/web/components/main/LogSection.tsx
  apps/web/components/main/NewLogButton.tsx
  apps/web/components/mypage/LogCard.tsx
  apps/web/components/mypage/replies/ReplieCard.tsx
  apps/web/components/mypage/savelog/SaveLog.tsx
Labels: enhancement, style, feat

#97 [Feat] 비밀번호 찾기 페이지, 로그아웃, 회원 탈퇴 구현 #96
  apps/web/app/find-password/page.tsx
  apps/web/components/find-password/ChangePasswordForm.tsx
  apps/web/components/find-password/FindPasswordForm.tsx
  apps/web/components/mypage/InfoList.tsx
  packages/ui/src/input.tsx
Labels: feat

#98 [Feat] 내가 쓴 댓글 페이지 라우팅과 삭제 기능 구현
  apps/web/app/mypage/replies/page.tsx
  apps/web/components/mypage/MainContainer.tsx
  apps/web/components/mypage/replies/ReplieCard.tsx
  apps/web/components/mypage/savelog/SaveLog.tsx
  apps/web/store/deleteReplySlice.ts
  apps/web/store/store.ts
  packages/ui/src/CardTop.tsx
Labels: feat

#99 [Fix] 내가 쓴 댓글 페이지의 충돌 문제로 인한 에러 수정
  apps/web/components/mypage/replies/ReplieCard.tsx
  apps/web/components/mypage/savelog/SaveLog.tsx
Labels: bug

#100 [Fix] 내가 쓴 댓글 페이지 Link 경로 수정
  apps/web/components/mypage/InfoList.tsx
Labels: bug

#101 [Fix] 빌드 시 에러로 인한 수정
  apps/docs/app/page.tsx
  apps/web/apis/log.ts
  apps/web/apis/logList.ts
  apps/web/app/api/mypage/savelog/route.ts
  apps/web/app/edit-mypage/page.tsx
  apps/web/app/mypage/recentlog/page.tsx
  apps/web/app/mypage/savelog/page.tsx
  apps/web/components/edit-mypage/EditMypageLayout.tsx
  apps/web/components/edit-mypage/ImageUpload.tsx
  apps/web/components/edit-mypage/InputForm.tsx
  apps/web/components/main/HotLogCard.tsx
  apps/web/components/main/HotLogCardList.tsx
  apps/web/components/main/LogCard.tsx
  apps/web/components/main/LogCardList.tsx
  apps/web/components/main/Pagination.tsx
  apps/web/components/mypage/LogCard.tsx
  apps/web/components/mypage/PageHeader.tsx
  apps/web/components/mypage/Visiting.tsx
  apps/web/components/mypage/replies/ReplieCard.tsx
  apps/web/components/mypage/savelog/SaveLog.tsx
  apps/web/components/mypage/savelog/SaveLogCard.tsx
  apps/web/types/hotLogCard.ts
  apps/web/types/logcard.ts
Labels: bug

#102 [Fix] 빌드 시 발생하는 에러로 인한 코드 수정
  apps/web/.eslintrc.js
  apps/web/apis/log.ts
  apps/web/app/log/page.tsx
  apps/web/app/mypage/layout.tsx
  apps/web/app/mypage/mylog/page.tsx
  apps/web/app/mypage/page.tsx
  apps/web/app/mypage/recentlog/page.tsx
  apps/web/app/mypage/savelog/page.tsx
  apps/web/components/edit-mypage/ImageUpload.tsx
  apps/web/components/edit-mypage/InputForm.tsx
  apps/web/components/mypage/LogCard.tsx
  apps/web/components/mypage/savelog/SaveLog.tsx
  apps/web/hooks/swr/useLogs.ts
  apps/web/next.config.js
  apps/web/types/log.ts
  packages/ui/package.json
Labels: bug

#105 [Chore] 배포를 위한 브랜치 병합 #95
  apps/web/components/latest-log/LogCardList.tsx
Labels: Chore, feat, urgent

#106 [Fix] 마이페이지 사이드 메뉴 및 이미지 수정하기 페이지 스타일 수정
  apps/web/app/edit-mypage/layout.tsx
  apps/web/app/edit-mypage/page.tsx
  apps/web/app/login/page.tsx
  apps/web/components/edit-mypage/ImageUpload.tsx
  apps/web/components/edit-mypage/InputForm.tsx
  apps/web/components/mypage/AsideContainer.tsx
  apps/web/components/mypage/InfoList.tsx
  apps/web/components/signup/SignupForm.tsx
  apps/web/public/default-user-profile.svg
  packages/ui/src/icon/IconComponents.tsx
Labels: style, refactor
